# Transcribing DNA into RNA

print('\nTranscribing DNA into RNA')

"""
Problem:
An RNA string is a string formed from the alphabet containing 'A', 'C', 'G', and 'U'.

Given a DNA string t corresponding to a coding strand, its transcribed RNA string u is 
formed by replacing all occurrences of 'T' in t with 'U' in u.

Given: A DNA string t having length at most 1000 nt.

Return: The transcribed RNA string of t.

input:
'GATGGAACTTGACTACGTAAATT'

output:
'GAUGGAACUUGACUACGUAAAUU'
"""

# Code
def transcription(segment_of_dna):
    segment_of_rna = ''

    for base in segment_of_dna:
        if base == 'T':
            segment_of_rna += 'U'
        else:
            segment_of_rna += base

    return segment_of_rna


# Solution
test = 'GACCTCTCGGCAGATGTGCTGCGAACCATCGGCCATGCCCCCTCCATAGGTTCCAATACACGCTTCATTTCCTCATTTCTACCCCCTTAATCAAACTGAGATGGGGCATGTCTCCCAAATAGTGGTGAACGGCACGGTGTTGGCAGGTCTGCTGGTACTATAGGTTCCTTGAGAGTTCTCATGATGCGAGAATAGACCATGGCTCAACATTGCCCGTTATGAAATCATAATAACGTAAATTCGATTATCCATACGATCGTCTACACCGCCTGTTACATCGGTTAGGTTTTAGCCCGAAGTCTCTAGGTCTTCGTATGGCAGTGCTAAACTGGGATATTATAGCATTCCGTACCGACTTTTCAGAGTGCCCAAGGTACGCAAGTAGAGCCGGGAGAACTCCGGGCGTGCGCCGAACAGGCCGATCGAGATTATTGGCTAAGAGAACTAAAAGCGTTAAACCCAACAGGCTCATTAAAATTTTGACTAGTCATTATGATGGGTATATCATAAGATCAGTTCGAACGCCTTGTTAGGAGGCGGCCGAGGAATTCAGTCTACACTCGTCATTTATGTTCGCTGCCTGAACCGCACGCTTAGTACGCTGGCCTCACCATTTGATTGGAAACCTGATCAAATCGTCGGCTAGTACATGGCCAGCCTTGTCGCATGACGGCTTCGAGATAGATATGTACGAAGCCTAAGATAAAGGTGTAAATCTGTTCGTGCCCGCGACCGAGAGGATATGCTGTCCAGCCCGGATTTCCATCAATGCGTTTTCCTTTAGTTCTGCGGGATTAGTGGCCCGATGTACTTTAGCCTCGGAGCGCGTGTCCTGACAAGATCGTTGCGCCTCAATAATTGGTGTGGCGTGTGGTACCTTGAACCACCTGAACGAGCAACCTTAGATAATCCGTTATTGGGCCTGCCCGGCCCTTTCCTTGAAAA'

solution = transcription(test)
print(solution)