# Fibonacci Numbers

print('\n' + 'Fibonacci Numbers')

"""
Problem
The Fibonacci numbers 0,1,1,2,3,5,8,13,21,34,… are generated by the following simple rule
    Fn = {Fn-1 + Fn-2, n > 1; 1, n = 1; 0, n = 0}

Given: A positive integer n≤25.

Return: The value of Fn.
"""

A = 23

# Definition
def fibonacci(n):
    if n == 0:
        return 0
    elif n == 1:
        return 1
    else:
        return fibonacci(n - 1) + fibonacci(n - 2)

# Solution
solution = fibonacci(A)

print(solution)