# Counting DNA Nucleotides

print('\n', 'Counting DNA Nucleotides')

"""
Problem
A string is simply an ordered collection of symbols selected from some alphabet and formed into a word; the length of a string is the number of symbols that it contains.

An example of a length 21 DNA string (whose alphabet contains the symbols 'A', 'C', 'G', and 'T') is "ATGCTTCAGAAAGGTCTTACG."

Given: A DNA string s of length at most 1000 nt.

Return: Four integers (separated by spaces) counting the respective number of times that the symbols 'A', 'C', 'G', and 'T' occur in s.
"""

S = 'GTGCTCTGTATAATCGGCAAGTTGCGTGTACTGCCCAAAGACCATACGGATACAGGCATCTACCAACAGGTGGCGTGACAATTAAGCGTTGCAATTGAACTTCGCGTTCTACCGGTTGAATATTACGACCCGCCTCTCAAGCCTCCGCATACTTCATTAGACCAAGGAAACAGACGCGTGACTTCGTCCGGTACGCGGTTCGACTGAACACGCGAATTTCAGGTGCATAAGGAGCAATTGCGCCAAGTAGCCTCGTAATATAATCGCTGGTGTGCGTCGGTCCACACTTCTGCACGACCATAACTGCTAGGGGCTTTGTTTTGGTGTTGTACTAGGCACCACTGAGTCTGGCTGCAACTTGCAAGCACCGGTGTCGTTGGTGGGCATTGCCTTCTTGCACTAAACAGCATGGTTAGTACCGTGGGTGTATACTGACAGTGCCGCTGGTGAACCCATCAGGACGACAAGGTATGGGAGCGCAGAGAAGGCTACAGGCGACCTGGTGCTCTTACGGTGGGTATCGCCCCAAAGCTCCTCGGCTGTTTCATTAGTTAACGTCCACACCTCGGTAAGATTCCAACTCGATAAGCAACAAGGGGTTATATGGACTGAGGTCTGTCGAGAGTTGTCGATAGAGTTCCGAACCCTGGTGATCTCTGACCTATACCGGCCCTGATCGGGTATACCTCAGCTTACCAGGAGACATGTACAAGCATAAGCCGCCGTCCGAAGGCGTGTGCGATTAAGAGTTTAGGGAGGTAGCCCGCGCTCGCTTAGATGCTATTTGAGAGGCTTTGTGTGCGCAGCAGGCCATTGGTGAGTACAGAAGGTATGCTGATTATCGCGGT'
NUCLEOBASES = ['A', 'C', 'G', 'T']

dic = {}

# Count bases
for base in NUCLEOBASES:
    cont = 0

    for nucleobase in S:
        if base == nucleobase:
            cont += 1
    
    dic[base] = cont

# Solution
solution = ''

for base in NUCLEOBASES:
    solution += str(dic[base]) + ' '

print(solution)